apiVersion: v1
kind: Namespace
metadata:
  name: test-calibrate-1-10g 
spec: {}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: system:openshift:scc:k10-generic-backup
  namespace: test-calibrate-1-10g  
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:k10-generic-backup
subjects:
- kind: ServiceAccount
  name: default
  namespace: test-calibrate-1-10g
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-calibrate-1
  namespace: test-calibrate-1-10g
  annotations:    
    k10.kasten.io/forcegenericbackup: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-calibrate-1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: workload-calibrate-1
    spec:
      containers:
      - command:
        - sh
        - -c
        - |
          cd /data
          count=10
          count2=$((1024*count))
          bigfile="big${count}G.bin"
          if [ ! -f $bigfile ]
          then            
            dd if=/dev/urandom of=$bigfile bs=1024K count=$count2;  
            md5sum $bigfile            
          fi
          tail -f /dev/null                    
        image: docker.io/alpine:latest
        imagePullPolicy: IfNotPresent
        name: workload-calibrate-1-container
        securityContext: 
          allowPrivilegeEscalation: false
          capabilities: 
            drop: 
            - "ALL"
            add: 
            - "CHOWN"
            - "DAC_OVERRIDE"
            - "FOWNER"
          runAsNonRoot: true 
          runAsUser: 1001 
          seccompProfile: 
            type: "RuntimeDefault"
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
        volumeMounts:
        - mountPath: /data
          name: data
      - args:
        - tail -f /dev/null
        command:
        - bash
        - -c
        image: gcr.io/kasten-images/kanister-tools:6.0.12
        imagePullPolicy: IfNotPresent
        name: kanister-sidecar
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - CHOWN
            - DAC_OVERRIDE
            - FOWNER
            drop:
            - ALL
          runAsNonRoot: true
          runAsUser: 1001
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - mountPath: /data/data
          name: data        
      securityContext:
        fsGroup: 1001     
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: calibrate-1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibrate-1
  namespace: test-calibrate-1-10g
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  # storageClassName: ebs-sc
