apiVersion: v1
kind: Namespace
metadata:
  name: basic-app  
spec: {}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: system:openshift:scc:k10-generic-backup
  namespace: basic-app  
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:k10-generic-backup
subjects:
- kind: ServiceAccount
  name: default
  namespace: basic-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-app
  namespace: basic-app
  labels:
    app: basic-app
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: basic-app
  template:
    metadata:
      labels:
        app: basic-app
    spec:
      containers:
      - name: basic-app-container   
        image: docker.io/alpine:latest
        resources:
            requests:
              memory: 256Mi
              cpu: 100m
        command: ["tail"]
        args: ["-f", "/dev/null"]
        securityContext: 
          allowPrivilegeEscalation: false
          capabilities: 
            drop: 
            - "ALL"
            add: 
            - "CHOWN"
            - "DAC_OVERRIDE"
            - "FOWNER"
          runAsNonRoot: true 
          runAsUser: 1001 
          seccompProfile: 
            type: "RuntimeDefault" 
        volumeMounts:
        - name: data
          mountPath: /data
      securityContext:
        fsGroup: 1001 
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: pvc-kasten
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-kasten
  namespace: badic-app
spec:
  # storageClassName: ocs-storagecluster-ceph-rbd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi